//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelTestForSchool.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupTime
    {
        public int ID { get; set; }
        public Nullable<int> IDTimetable { get; set; }
        public Nullable<int> IDGroup { get; set; }
        public bool IsVisited { get; set; }
    
        public virtual GroupStatistic GroupStatistic { get; set; }
        public virtual Timetable Timetable { get; set; }
    }
}
